/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mcc_MccGniInterface */

#ifndef _Included_mcc_MccJniInterface
#define _Included_mcc_MccJniInterface
#ifdef __cplusplus
extern "C" {
#endif

#define MCCERRORVALUE -99999 // matches a similar variable in the java code.
/*
 * Class:     mcc_MccGniInterface
 * Method:    haveLibrary
 * Signature: ()Z
 */
//JNIEXPORT jboolean JNICALL Java__mcc_MccJniInterface_haveLibrary
//  (JNIEnv *, jclass);

/*
 * Class:     mcc_MccGniInterface
 * Method:    getNumBoards
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_mcc_MccJniInterface_jniGetNumBoards
  (JNIEnv *, jclass);

/*
 * Class:     mcc_MccGniInterface
 * Method:    getBoardName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mcc_MccJniInterface_jniGetBoardName
  (JNIEnv *, jclass, jint);

JNIEXPORT jdouble JNICALL Java_mcc_MccJniInterface_jniReadVoltage
  (JNIEnv *env, jclass, jint iBoard, jint iChannel, jint scale);

/**
 * Get the last error code from whatever operation was performed.
 */
JNIEXPORT jint JNICALL Java_mcc_MccJniInterface_jniGetLastErrorCode
  (JNIEnv *env, jclass);

/**
 * Get a cb error string from an error code.
 */
JNIEXPORT jstring JNICALL Java_mcc_MccJniInterface_jniGetErrorString
(JNIEnv *env, jclass, jint errorCode);

#ifdef __cplusplus
}
#endif
#endif
